# Generated by Django 5.2.3 on 2025-06-27 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_type', models.CharField(choices=[('tourism_selection', '관광지 선택'), ('user_profile', '사용자 프로필'), ('event', '이벤트'), ('general', '일반')], default='general', max_length=50)),
                ('data', models.JSONField(default=dict, verbose_name='QR 코드 데이터')),
                ('file_path', models.CharField(max_length=500, verbose_name='파일 경로')),
                ('filename', models.CharField(blank=True, max_length=200, verbose_name='파일명')),
                ('url', models.URLField(verbose_name='접근 URL')),
                ('gcp_url', models.URLField(blank=True, verbose_name='GCP Storage URL')),
                ('related_id', models.CharField(blank=True, max_length=100, verbose_name='연관 ID')),
                ('is_active', models.BooleanField(default=True)),
                ('access_count', models.IntegerField(default=0, verbose_name='접근 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='만료일')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR 코드',
                'verbose_name_plural': 'QR 코드 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
