# Generated by Django 5.2.3 on 2025-06-27 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firestore_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='관광지명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='주소')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='카테고리')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='태그')),
                ('contact_info', models.CharField(blank=True, max_length=200, verbose_name='연락처')),
                ('website', models.URLField(blank=True, verbose_name='웹사이트')),
                ('opening_hours', models.TextField(blank=True, verbose_name='운영시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(default=dict, verbose_name='원본 데이터')),
            ],
            options={
                'verbose_name': '관광지',
                'verbose_name_plural': '관광지 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserTourismSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='세션 ID')),
                ('original_query', models.TextField(verbose_name='원본 쿼리')),
                ('processed_query', models.TextField(blank=True, verbose_name='처리된 쿼리')),
                ('ai_analysis', models.JSONField(default=dict, verbose_name='AI 분석 결과')),
                ('qr_code_url', models.URLField(blank=True, verbose_name='QR 코드 URL')),
                ('qr_code_path', models.CharField(blank=True, max_length=500, verbose_name='QR 코드 파일 경로')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_spots', models.ManyToManyField(to='tourism.tourismspot', verbose_name='선택된 관광지')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 관광지 선택',
                'verbose_name_plural': '사용자 관광지 선택 기록',
                'ordering': ['-created_at'],
            },
        ),
    ]
